#include "MixedMode.r"
#include "Types.r"      /* BNDL / FREF / STR templates for the Finder icon */

/*
 * 'sdev' code resource = a Mixed Mode routine descriptor wrapping our PPC PEF.
 * ProcInfo for the Control Strip entry point:
 *     pascal long MiniAudioStrip(long message, long params,
 *                                Rect *statusRect, GrafPtr statusPort)
 *   kPascalStackBased            = 0x0000
 *   result  long   (4) -> 3<<4   = 0x0030
 *   param1  long   (4) -> 3<<6   = 0x00C0
 *   param2  long   (4) -> 3<<8   = 0x0300
 *   param3  Rect*  (4) -> 3<<10  = 0x0C00
 *   param4  GrafPtr(4) -> 3<<12  = 0x3000
 *                                 --------
 *                       ProcInfo = 0x00003FF0
 * (Same signature as the working UT-launcher CSM.)
 */
type 'sdev' as 'rdes';

resource 'sdev' (128, "Mini Audio", locked) {
    0x00003FF0,
    $$Read("MiniAudioStrip.pef")
};

/* Control Strip state icons (16x16 ics#/ics4, IDs 128/129/130) + the Finder
 * file icon (32x32 ICN#/icl4, ID 256). Generated by make-icons.py. */
#include "mini_audio_strip_icons.r"

/* Finder icon for the module file itself (creator 'MmAc', type 'sdev').
 * NOTE: for the Finder to DISPLAY it, the file's bundle bit must be set and the
 * desktop rebuilt — the cross-build does not set that automatically. */
type 'MmAc' as 'STR ';
resource 'MmAc' (0) {
    "Mini Audio Control Strip"
};

resource 'FREF' (256) {
    'sdev', 0, ""
};

resource 'BNDL' (256) {
    'MmAc', 0,
    { 'ICN#', { 0, 256 },
      'FREF', { 0, 256 } }
};
