#!/usr/bin/env python3
"""Convert Claude Design's PNGs (design/png/*.png) to Mac icon resources.

Writes mini_audio_strip_icons.r with, per icon, the full small/large suite:
  state icons 16x16 (IDs 128 spk / 129 hph / 130 mute): ics# + ics4 + ics8
  file icon  32x32 (ID 256):                             ICN# + icl4 + icl8
The CSM loads them via SBGetDetachIconSuite (svAllSmallData) and PlotIconSuite,
which picks the deepest member <= display depth: ics8/icl8 (256-colour) on a
colour display, ics4/icl4 (16-colour) at 16 colours, ics#/ICN# (1-bit+mask) lower.

8-bit indices map to the classic Mac System palette ('clut' 8): indices 0..214 are
a 6x6x6 reverse-order colour cube (index 0 = white), index 255 = black. We map each
pixel to the nearest of those 216 cube colours — the cube portion is exactly known;
we avoid the 215..254 ramp indices (less certain) to be safe.
Alpha < 128 -> transparent (mask 0). Requires Pillow.
"""
from PIL import Image

HEX = "0123456789ABCDEF"
MAC16 = [(255,255,255),(252,243,5),(255,100,3),(221,9,7),(242,8,132),(71,0,165),
         (0,0,211),(2,171,234),(31,183,20),(0,100,18),(86,44,5),(144,113,58),
         (192,192,192),(128,128,128),(64,64,64),(0,0,0)]

def mac8_cube():
    pal = {}
    for i in range(215):
        pal[i] = ((5 - i//36)*51, (5 - (i//6)%6)*51, (5 - i%6)*51)
    pal[255] = (0,0,0)
    return pal
CUBE = mac8_cube()

def nearest(rgb, table):
    r,g,b = rgb
    best,bi = 1<<30,0
    for idx,(R,G,B) in (table.items() if isinstance(table,dict) else enumerate(table)):
        d=(r-R)*(r-R)+(g-G)*(g-G)+(b-B)*(b-B)
        if d<best: best,bi=d,idx
    return bi

def load(name):
    im = Image.open(f"design/png/{name}.png").convert("RGBA")
    n = im.width
    px = im.load()
    cells=[]  # per pixel: (opaque, idx8, idx4, dark)
    for y in range(n):
        for x in range(n):
            r,g,b,a = px[x,y]
            if a < 128:
                cells.append((0,0,0,0)); continue
            i8 = nearest((r,g,b), CUBE)
            i4 = nearest((r,g,b), MAC16)
            dark = 1 if (r*299+g*587+b*114)//1000 < 128 else 0
            cells.append((1,i8,i4,dark))
    return n, cells

def one_bit(n, cells):
    rb=(n+7)//8
    icon,mask=bytearray(),bytearray()
    for y in range(n):
        ib=[0]*rb; mb=[0]*rb
        for x in range(n):
            op,_,_,dk = cells[y*n+x]
            if op and dk: ib[x//8]|=1<<(7-x%8)
            if op:        mb[x//8]|=1<<(7-x%8)
        icon+=bytes(ib); mask+=bytes(mb)
    return bytes(icon+mask)

def four_bit(n, cells):
    out=bytearray()
    for y in range(n):
        for x in range(0,n,2):
            hi=cells[y*n+x][2]; lo=cells[y*n+x+1][2]
            out.append((hi<<4)|lo)
    return bytes(out)

def eight_bit(n, cells):
    return bytes(cells[i][1] for i in range(n*n))

def hexblock(b, ind="        "):
    out=[]
    for i in range(0,len(b),16):
        c=b[i:i+16]
        out.append(ind+'$"'+" ".join(f"{c[j]:02X}{c[j+1]:02X}" for j in range(0,len(c)-1,2))+('' if len(c)%2==0 else f" {c[-1]:02X}")+'"')
    return "\n".join(out)

ICONS=[(128,"speaker-16","ics#","ics4","ics8"),
       (129,"headphones-16","ics#","ics4","ics8"),
       (130,"mute-16","ics#","ics4","ics8"),
       (256,"file-icon-32","ICN#","icl4","icl8")]

def main():
    out=["/* GENERATED by png-to-icons.py from design/png/*.png — do not hand-edit. */",""]
    for rid,name,t1,t4,t8 in ICONS:
        n,cells=load(name)
        out+=[f"data '{t1}' ({rid}) {{", hexblock(one_bit(n,cells)), "};", ""]
        out+=[f"data '{t4}' ({rid}) {{", hexblock(four_bit(n,cells)), "};", ""]
        out+=[f"data '{t8}' ({rid}) {{", hexblock(eight_bit(n,cells)), "};", ""]
    open("mini_audio_strip_icons.r","w").write("\n".join(out))
    print("wrote mini_audio_strip_icons.r")
    # report distinct 8-bit colours surviving per icon (gradient-collapse check)
    for rid,name,_,_,_ in ICONS:
        n,cells=load(name)
        used=sorted({c[1] for c in cells if c[0]})
        print(f"  {name}: {len(used)} distinct cube colours after mapping")

if __name__=="__main__":
    main()
